### ISSUE TITLE
请问 rtmdet_l_8xb32-300e_coco_20220719_112030-5a0be7c4.pth 和 merge.pth 能从哪下载

### ISSUE THREAD

**Issue by ShixuanLiu1124** [liuyanyi/sam-with-mmdet#1]

**Comment by eleanor11** [comment]
https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_l_8xb32-300e_coco/rtmdet_l_8xb32-300e_coco_20220719_112030-5a0be7c4.pth

**Comment by ShixuanLiu1124** [comment]
> 

感谢
